spring:
  application:
    name: numbers-client
  security:
    user:
      password: password
  cloud:
    services:
      registrationMethod: route

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka